### ISSUE TITLE
error at step 3

### ISSUE THREAD

**Issue by hoangmnsd** [Li4n0/hugo_encryptor#10]
Hi @Li4n0 
Thank you for this solution, I'm follow the steps but get stuck here. Can you help me to figure out it?
`
Traceback (most recent call last):
  File "F:/Sites/hugo_encryptor/hugo-encryptor.py", line 133, in <module>
    f.write(str(soup))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u1ee5' in position 9066: character maps to <undefined>
`

**Comment by OrangeSodahub** [comment]
run the .py file with PythonIDE then that will not be problem
not the VS complier

**Comment by Li4n0** [comment]
As @OrangeSodahub says.
